### ISSUE TITLE
AppSet diff support

### ISSUE THREAD

**Issue by KalenWessel** [zapier/kubechecks#227]
Are there any plans to enhance the diffing capabilities for ArgoCD appsets in the future?

Currently, kubechecks partially supports appsets. If a `values.yaml` file referenced by an appset is modified, kubechecks can provide diffs for all affected apps. However, when changes are made to the `appset.yaml`  `values: |` section, kubechecks only displays a diff of the values within the `appset.yaml` file. It doesn't indicate how these changes will impact the underlying apps.

To work around this we try to avoid making changes inside the `appset.yaml` files as much as possible but isn't always possible due to templating needs.

**Comment by Greyeye** [comment]
We need to modify the current approach to building the diff. When `diff.Check` is executed, it runs the diff only for the specific resource that triggered the request (e.g., if an application is modified, it runs a diff against that application; if an ApplicationSet is modified, it runs a diff against the ApplicationSet).

However, since ApplicationSets are responsible for generating applications, any changes to an ApplicationSet should also trigger a simulation/diff for the affected applications. Implementing this requires Kubechecks to be aware of the selectors and generators configured on the ArgoCD server. I have yet to figure this out and am not even sure it is possible to gather these. 

## Example Workflow:
* ApplicationSet Modification: A change is detected in an ApplicationSet.
Fetch Dependencies: Kubechecks queries ArgoCD to retrieve all applications generated by this ApplicationSet.
* Run Diff: Simulate and run a diff for both the ApplicationSet and its generated applications.
* Report: Aggregate the results and report back to the PR/MR, indicating the impact of the changes.

## Dev note

Currently, the localdev/Tile setup loads the test_appsets directly into the local development cluster. However, I'll need to modify this process so that Terraform loads the appsets and associated applications into the demo VCS repository. This will be followed by modifying the local development ArgoCD instance to read from this demo repository.

**Comment by Greyeye** [comment]
seems that there is already a discussion on [ArgoCD Project](https://github.com/argoproj/argo-cd/issues/10895) on this matter.

**Comment by Greyeye** [comment]
[PR](https://github.com/zapier/kubechecks/pull/241) raised

**Comment by Greyeye** [comment]
feature added and release in [v.1.7.0](https://github.com/zapier/kubechecks/releases/tag/v1.7.0)

**Comment by Greyeye** [comment]
feature added with [v1.7.0](https://github.com/zapier/kubechecks/releases/tag/v1.7.0)
